if(NOT DEFINED LEGACY_CONFIG_ROOT)
    message(FATAL_ERROR "LEGACY_CONFIG_ROOT is required")
endif()

set(manifest "${LEGACY_CONFIG_ROOT}/manifest.txt")
if(NOT EXISTS "${manifest}")
    message(FATAL_ERROR "Missing legacy fixture manifest: ${manifest}")
endif()

file(STRINGS "${manifest}" lines)
set(source_commit "")
set(fixture_count 0)
foreach(line IN LISTS lines)
    if(line MATCHES "^source_commit ([0-9a-f]+)$")
        set(source_commit "${CMAKE_MATCH_1}")
        string(LENGTH "${source_commit}" source_commit_length)
        if(NOT source_commit_length EQUAL 40)
            message(FATAL_ERROR "Legacy fixture source commit must be 40 hexadecimal characters")
        endif()
    elseif(line MATCHES "^sha256 ([0-9a-f]+) ([A-Za-z0-9._-]+\\.json)$")
        set(expected_hash "${CMAKE_MATCH_1}")
        set(filename "${CMAKE_MATCH_2}")
        string(LENGTH "${expected_hash}" expected_hash_length)
        if(NOT expected_hash_length EQUAL 64)
            message(FATAL_ERROR "Legacy fixture hash for ${filename} must be 64 hexadecimal characters")
        endif()
        set(path "${LEGACY_CONFIG_ROOT}/${filename}")
        if(NOT EXISTS "${path}")
            message(FATAL_ERROR "Missing pinned legacy fixture: ${filename}")
        endif()
        file(SHA256 "${path}" actual_hash)
        if(NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "Legacy fixture drift: ${filename}")
        endif()
        math(EXPR fixture_count "${fixture_count} + 1")
    elseif(NOT line STREQUAL "" AND NOT line MATCHES "^#")
        message(FATAL_ERROR "Malformed legacy fixture manifest line: ${line}")
    endif()
endforeach()

if(source_commit STREQUAL "")
    message(FATAL_ERROR "Legacy fixture manifest has no source commit")
endif()
if(NOT fixture_count EQUAL 14)
    message(FATAL_ERROR "Expected 14 pinned legacy fixtures, found ${fixture_count}")
endif()
